spring:
  application:
    name: lms-lti-crosslist
  session:
    store-type: none
  config.import: optional:${app.fullFilePath}/${app.overridesFileName}, optional:${app.fullFilePath}/security.properties, classpath:canvas.properties, optional:classpath:git.properties, optional:classpath:denodo.properties, classpath:lti-registrations.properties
  data:
    rest:
      base-path: /rest
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
      jadira:
        usertype:
          autoRegisterUserTypes: true
  datasource:
    url: ${lms.db.url}
    username: ${lms.db.user}
    password: ${lms.db.password}
    type: ${lms.db.poolType}
  cloud.vault.enabled: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oauth.tokenprovider.url}/.well-known/jwks.json
lms-lti-crosslist:
  version: @app.version@
  env: ${app.env}
  adminRoles: http://purl.imsglobal.org/vocab/lis/v2/institution/person#Administrator

server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 30m

app:
  env: dev
  fullFilePath: file:/usr/src/app/config
  overridesFileName: overrides.properties

management:
  endpoint.lms.enabled: true
  endpoints.web.exposure.include: health,lms
  health.redis.enabled: false
  info.java.enabled: true

---

spring:
  config.activate.on-profile: redis-session
  session:
    store-type: redis
    redis.namespace: lms-lti-crosslist-@app.version@:session
management.health.redis.enabled: true

---

spring:
  config:
    activate.on-profile: vault
    import: vault://
  cloud.vault:
    enabled: true
    config:
      lifecycle.lease-endpoints: leases
    generic:
      enabled: false
    kv:
      enabled: true
      backend: ua-vpit/enterprise-systems/lms/kv
      application-name: lms-lti-crosslist

---

spring:
  config:
    activate.on-profile: swagger
springdoc:
  api-docs:
    enabled: true
    path: /api/v3/api-docs
  cache.disabled: true
  packagesToScan: edu.iu.uits.lms.crosslist.controller.rest
  swagger-ui:
    enabled: false
    disable-swagger-default-url: true
    path: /api/swagger-ui.html
    # Setting supportedSubmitMethods to an empty list is what turns off the "try it out" button
    #    supportedSubmitMethods:
    oauth:
      clientId: ${oauth.tokenprovider.clientId}
  oAuthFlow:
    authorizationUrl: ${oauth.tokenprovider.url}/oauth/authorize
    tokenUrl: ${oauth.tokenprovider.accessTokenUri}
