spring:
  application:
    name: lms-lti-crosslist
  profiles:
    active: redis
  session:
    store-type: none
#  output:
#    ansi:
#      enabled: ALWAYS
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oauth.tokenprovider.url}/.well-known/jwks.json
lms-lti-crosslist:
  version: @app.version@
  env: ${app.env}

---

spring:
  profiles: redis
  session:
    store-type: redis
    redis.namespace: lms-lti-crosslist-${app.version}:session