spring:
  application:
    name: lms-lti-crosslist
  profiles:
    active: redis-session
  session:
    store-type: none
#  output:
#    ansi:
#      enabled: ALWAYS
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oauth.tokenprovider.url}/.well-known/jwks.json
lms-lti-crosslist:
  version: @app.version@
  env: ${app.env}

server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 30m

---

spring:
  profiles: redis-session
  session:
    store-type: redis
    redis.namespace: lms-lti-crosslist-${app.version}:session