spring:
  application:
    name: lms-lti-crosslist
  session:
    store-type: none
  config.import: optional:${app.fullFilePath}/${app.overridesFileName}, optional:${app.fullFilePath}/security.properties, classpath:canvas.properties, optional:classpath:git.properties, classpath:lti-registrations.properties
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
      jadira:
        usertype:
          autoRegisterUserTypes: true
  datasource:
    url: ${lms.db.url}
    username: ${lms.db.user}
    password: ${lms.db.password}
    type: ${lms.db.poolType}
  cloud.vault.enabled: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oauth.tokenprovider.url}/.well-known/jwks.json
lms-lti-crosslist:
  version: @app.version@
  env: ${app.env}
  adminRoles: Account Admin, Administrator, Dept Admin, SC Supervisors

server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 30m

app:
  env: dev
  fullFilePath: file:/usr/src/app/config
  overridesFileName: overrides.properties

management:
  endpoint.info.enabled: true
  endpoints.web.exposure.include: health,info
  health.redis.enabled: false

---

spring:
  config.activate.on-profile: redis-session
  session:
    store-type: redis
    redis.namespace: lms-lti-crosslist-@app.version@:session
management.health.redis.enabled: true

---

spring:
  config:
    activate.on-profile: vault
    import: vault://
  cloud.vault:
    enabled: true
    config:
      lifecycle.lease-endpoints: sysleases
    generic:
      enabled: false
    kv:
      enabled: true
      backend: ua-vpit/enterprise-systems/lms/kv
      application-name: lms-lti-crosslist

---

spring:
  config:
    activate.on-profile: swagger
    import: classpath:lti-api-config.properties
springdoc:
  swagger-ui:
    oauth:
      clientId: ${oauth.tokenprovider.clientId}
  oAuthFlow:
    authorizationUrl: ${oauth.tokenprovider.url}/oauth/authorize
    tokenUrl: ${oauth.tokenprovider.accessTokenUri}
