# Description
# -----------
# This workflow builds and releases the Docker image to Harbor, then deploys out to the kubernetes environment.
#
# Setup
# -----
# 1. Create the following secrets inside GitHub:
#    - LMS_GH_TOKEN (Personal access token for the lmsgit user that has read access to other repositories)
#    - LMS_MAVEN_SETTINGS (Base64 encoded settings.xml file)
#    - LMS_REGISTRY_PASSWORD (Registry password - push access)
#    - LMS_REGISTRY_USERNAME (Registry username)
# 2. Create the following environments, representative of the deployments:
#    - reg
#    - stg
#    - prd
# 3. Create the following secrets in each of the above environments
#    - LMS_KUBECONFIG_DEPLOYER (Base64 encoded kubernetes deployment service account for the appropriate cluster)
# 4. Create the following variables in each of the above environment
#    - DOCKER_TAG (tag name for the docker image that will be deployed i.e. stable, unstable-reg, etc)

name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      server_env:
        type: choice
        required: true
        options:
          - reg
          - stg
          - prd
        description: Select deployment env
        default: reg
      helm_deployer_branch:
        required: true
        description: Indicate the branch that contains the helm deployment files
        default: develop

env:
  TZ: America/New_York
  IMAGE_REPO: registry.docker.iu.edu/lms/lms-lti-crosslist
  IMAGE_TAG: registry.docker.iu.edu/lms/lms-lti-crosslist:${{ vars.DOCKER_TAG }}
  DIGEST_REPO: registry.docker.iu.edu/lms/lms-lti-crosslist@sha256
  KUBE_NS: ua-vpit--enterprise-systems--lms--helm-release
  DEPLOY_DIR: crosslisting
  JAR_FILE: lms-lti-crosslist.jar
  K8S_RELEASE_PREFIX: lms-lti-crosslist

jobs:
  mvn_build:
    name: Maven Build
    runs-on: self-hosted
    container:
      image: maven:3.9.4-eclipse-temurin-17
    environment: ${{ github.event.inputs.server_env }}
    steps:
      - name: Clone GitHub root repository
        uses: actions/checkout@v4
        with:
          repository: iu-uits-es/ess-lms-canvas-standalone-apps
          ref: ${{ github.event.inputs.helm_deployer_branch }}
          token: ${{ secrets.LMS_GH_TOKEN }}
          github-server-url: https://github.iu.edu
#          path: source
      - name: Clone GitHub tool repository
        uses: actions/checkout@v4
        with:
          path: tools/${{ env.DEPLOY_DIR }}
      - name: mvn setup
        run: mkdir /root/.m2
      - name: Create maven settings.xml
        run: echo -n '${{ secrets.LMS_MAVEN_SETTINGS }}' | base64 -d > /root/.m2/settings.xml
      - name: Maven Build
        run: mvn clean install -P 'denodo,it12'
        working-directory: tools/${{ env.DEPLOY_DIR }}
      - name: copy jar file
        run: |
          mkdir -p deployments/${{ env.DEPLOY_DIR }}/lib
          cp tools/${{ env.DEPLOY_DIR }}/target/${{ env.JAR_FILE }} deployments/${{ env.DEPLOY_DIR }}/lib/${{ env.JAR_FILE }}
      - name: build/push docker image
        run: |
          mvn clean install -P docker-push -D dockerfile.username=${{ secrets.LMS_REGISTRY_USERNAME }} \
            -D dockerfile.password=${{ secrets.LMS_REGISTRY_PASSWORD }} -D docker_repository_base=registry.docker.iu.edu/lms/ \
            -D docker_tag=${{ vars.DOCKER_TAG }}
        working-directory: deployments/${{ env.DEPLOY_DIR }}
  deploy:
    name: Deploy to Kubernetes
    needs: [ mvn_build ]
    runs-on: self-hosted
    environment: ${{ github.event.inputs.server_env }}
    container:
#      image: registry.docker.iu.edu/library/kube-deployer:3.11.0
      image: registry.docker.iu.edu/library/kube-deployer:3.10.2
      credentials:
        username: ${{ secrets.LMS_REGISTRY_USERNAME }}
        password: ${{ secrets.LMS_REGISTRY_PASSWORD }}
    steps:
      - name: Clone GitHub repository
        uses: actions/checkout@v4
        with:
          repository: iu-uits-es/ess-lms-canvas-standalone-apps
          ref: ${{ github.event.inputs.helm_deployer_branch }}
          token: ${{ secrets.LMS_GH_TOKEN }}
          github-server-url: https://github.iu.edu
      - name: Create KUBECONFIG file for the cluster
        run: |
          echo -n '${{ secrets.LMS_KUBECONFIG_DEPLOYER}}' | base64 -d > /root/.kube/config
          chmod 400 /root/.kube/config
      - name: Get Docker Image SHA
        id: get-docker-image-sha
        run: |
          echo "DOCKER_IMAGE_SHA=$(skopeo inspect --creds '${{ secrets.LMS_REGISTRY_USERNAME }}:${{ secrets.LMS_REGISTRY_PASSWORD }}' \
            docker://${{ env.IMAGE_TAG }} | jq -rc '.Digest' | awk -F':' '{ print $2 }')" >> "$GITHUB_OUTPUT"
      - name: Deploy
        env:
          KUBECONFIG: /root/.kube/config
        working-directory: deployments/${{ env.DEPLOY_DIR }}
        run: |
          helm upgrade ${{ env.K8S_RELEASE_PREFIX }}-${{ github.event.inputs.server_env }} ../../k8s \
            --values helm-common.yaml,helm-${{ github.event.inputs.server_env }}.yaml --install -n ${{ env.KUBE_NS }} \
            --set image.repository="${{ env.DIGEST_REPO }}",image.tag="${{ steps.get-docker-image-sha.outputs.docker_image_sha }}",image.tagName="${{ vars.DOCKER_TAG }}" \
            --wait --timeout 15m